const path = require('path')
const {promises: fs} = require('fs')
const {STATIC_PATH} = require('material-design-icons')
const glob = require('glob')
const svgr = require('@svgr/core').default

const outputPath = process.argv.slice(2)[0]

function template({template}, _opts, {componentName, jsx}) {
  const typeScriptTemplate = template.smart({plugins: ['typescript']})
  return typeScriptTemplate.ast`export function ${componentName}(props: SVGProps<SVGSVGElement>) {return ${jsx}}`
}

function snakeCaseToPascalCase(str) {
  return str.replace(/(([-_]|^)[a-z])/gi, group =>
    group
      .toUpperCase()
      .replace('-', '')
      .replace('_', '')
  )
}

glob(`${STATIC_PATH}/*/svg/production/*_48px.svg`, async (err, files) => {
  if (err) throw err

  const sources = []
  const icons = {}

  for (const file of files) {
    const name = /ic_(.*?)_48px/i.exec(path.basename(file))[1]

    if (icons[name]) continue

    const pascalCaseName = snakeCaseToPascalCase(name)
    const svgBuffer = await fs.readFile(file)
    const source = await svgr(
      svgBuffer,
      {
        dimensions: false,
        template
      },
      {componentName: `MaterialIcon${pascalCaseName}`}
    )

    icons[name] = true
    sources.push(source)
  }

  await fs.writeFile(
    outputPath,
    `// THIS FILE IS AUTOGENERATED, EDIT WITH CAUTION

// This file includes Material Design Icons converted to React components.
// Material Design Icons are licensed under the Apache License Version 2.0:
// https://github.com/google/material-design-icons/blob/master/LICENSE

import React, {SVGProps} from 'react'

${sources.join('\n\n')}`
  )
})
